name: Branch Freeze Enforcement

on:
  workflow_dispatch:

jobs:
  branch-freeze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set branch info
        id: set_info
        run: |
          BRANCH="master"                 # Blocked branch
          START_FREEZE="2024-10-03 11:10"
          END_FREEZE="2024-10-03 11:59"

          echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
          echo "START_FREEZE=${START_FREEZE}" >> $GITHUB_ENV
          echo "END_FREEZE=${END_FREEZE}" >> $GITHUB_ENV

      - name: Get current time
        id: get_time
        run: |
          CURRENT_DATE_TIME=$(TZ="Asia/Kolkata" date +'%Y-%m-%d %H:%M')
          echo "Current date and time: $CURRENT_DATE_TIME"
          echo "current_time=$CURRENT_DATE_TIME" >> $GITHUB_ENV

      - name: Check freeze period
        run: |
          START_FREEZE="${{ env.START_FREEZE }}"
          END_FREEZE="${{ env.END_FREEZE }}"
          CURRENT_DATE_TIME="${{ env.current_time }}"

          # Check if current time is within the freeze period
          if [[ "$CURRENT_DATE_TIME" > "$START_FREEZE" && "$CURRENT_DATE_TIME" < "$END_FREEZE" ]]; then
            echo "We are within the freeze period. Exiting with error."
            exit 1  # Exit with error to block the push
          else
            echo "Outside of freeze period, no action required."
          fi

      - name: Send email notification
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}  # Store your API key in GitHub Secrets
        run: |
          FROM_EMAIL="krishnasmart9527@gmail.com"
          TO_EMAILS="krishnasmart9527@gmail.com"
          SUBJECT="Branch freeze notification"
          BODY="The master branch is currently locked for the freeze period from 11:10 AM to 11:59 AM."

          # Sending the email using SendGrid
          curl --request POST \
            --url https://api.sendgrid.com/v3/mail/send \
            --header "Authorization: Bearer $SENDGRID_API_KEY" \
            --header 'Content-Type: application/json' \
            --data '{
              "personalizations": [
                {
                  "to": [
                    {
                      "email": "'"$TO_EMAILS"'"
                    }
                  ]
                }
              ],
              "from": {
                "email": "'"$FROM_EMAIL"'"
              },
              "subject": "'"$SUBJECT"'",
              "content": [
                {
                  "type": "text/plain",
                  "value": "'"$BODY"'"
                }
              ]
            }'
