name: Branch Freeze Check

on:
  push:
    branches:
      - master  # Only runs on the 'master' branch
  workflow_dispatch: # Allows manual trigger if needed

jobs:
  freeze-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get current branch name
      id: get_branch
      run: echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

    - name: Check if branch is frozen (local time)
      run: |
        FROZEN_BRANCH="master"
        CURRENT_BRANCH="${{ env.branch }}"

        # Set the timezone to your local timezone (e.g., Asia/Kolkata)
        TZ="Asia/Kolkata"
        export TZ

        # Get current date and time in local timezone (format: YYYY-MM-DD HH:MM)
        CURRENT_DATE_TIME=$(date +'%Y-%m-%d %H:%M')

        # Define freeze period (start and end time in your local timezone)
        FREEZE_START="2024-10-03 10:53"
        FREEZE_END="2024-10-03 11:00"

        echo "Current date and time: $CURRENT_DATE_TIME"
        echo "Freeze period: $FREEZE_START to $FREEZE_END"

        if [ "$CURRENT_BRANCH" == "$FROZEN_BRANCH" ]; then
          # Correct condition to check if current time is within freeze period
          if [[ "$CURRENT_DATE_TIME" > "$FREEZE_START" && "$CURRENT_DATE_TIME" < "$FREEZE_END" ]]; then
            echo "Branch is frozen! Pushes are not allowed between $FREEZE_START and $FREEZE_END (local time)."
            exit 1  # Exit with error to fail the pipeline
          else
            echo "Push is allowed. Outside of freeze time."
          fi
        else
          echo "Not on the frozen branch."
        fi
