name: Branch Freeze Enforcement

on:
  workflow_dispatch:

jobs:
  branch-freeze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set repository and branch info
        id: set_info
        run: |
          # Set your GitHub organization and repository
          GITHUB_ORG="your-github-org"  # Replace with your GitHub organization
          GITHUB_REPO="python-freeze-unfreeze-2"  # Your repository name
          BRANCH="master"  # Blocked branch
          START_FREEZE="2024-10-03 11:30"
          END_FREEZE="2024-10-03 11:59"

          echo "GITHUB_ORG=${GITHUB_ORG}" >> $GITHUB_ENV
          echo "GITHUB_REPO=${GITHUB_REPO}" >> $GITHUB_ENV
          echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
          echo "START_FREEZE=${START_FREEZE}" >> $GITHUB_ENV
          echo "END_FREEZE=${END_FREEZE}" >> $GITHUB_ENV

      - name: Get current time
        id: get_time
        run: |
          CURRENT_DATE_TIME=$(TZ="Asia/Kolkata" date +'%Y-%m-%d %H:%M')
          echo "Current date and time: $CURRENT_DATE_TIME"
          echo "current_time=$CURRENT_DATE_TIME" >> $GITHUB_ENV

      - name: Check freeze period
        run: |
          START_FREEZE="${{ env.START_FREEZE }}"
          END_FREEZE="${{ env.END_FREEZE }}"
          CURRENT_DATE_TIME="${{ env.current_time }}"

          # Check if current time is within the freeze period
          if [[ "$CURRENT_DATE_TIME" > "$START_FREEZE" && "$CURRENT_DATE_TIME" < "$END_FREEZE" ]]; then
            echo "We are within the freeze period."
          else
            echo "Outside of freeze period, no action required."
            exit 0
          fi

      - name: Lock the branch in the repository
        env:
          GITHUB_TOKEN: ${{ secrets.FULL_PERMISSION_PAT }}  # Use your PAT here
        run: |
          # Using GitHub CLI to set branch protection rules
          gh api \
            --method PUT \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ env.GITHUB_ORG }}/${{ env.GITHUB_REPO }}/branches/${{ env.BRANCH }}/protection \
            -F "required_status_checks[strict]=true" \
            -F "required_status_checks[contexts][]='continuous-integration/travis-ci'" \
            -F "enforce_admins=true" \
            -F "required_pull_request_reviews[dismiss_stale_reviews]=true" \
            -F "required_pull_request_reviews[require_code_owner_reviews]=true" \
            -F "required_pull_request_reviews[required_approving_review_count]=2" \
            -F "required_linear_history=true" \
            -F "lock_branch=true" \
            -F "allow_force_pushes=true" \
            -F "allow_deletions=true" \
            -F "block_creations=true" \
            -F "required_conversation_resolution=true"

          echo "Successfully set branch protection rules for ${{ env.BRANCH }} in ${{ env.GITHUB_REPO }}."
