name: Branch Freeze Check

on:
  push:
    branches:
      - master  # Only runs on the 'master' branch
  workflow_dispatch: # Allows manual trigger if needed

jobs:
  freeze-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get current branch name
      id: get_branch
      run: echo "::set-output name=branch::$(git rev-parse --abbrev-ref HEAD)"

    - name: Check if branch is frozen
      run: |
        FROZEN_BRANCH="master"
        CURRENT_BRANCH="${{ steps.get_branch.outputs.branch }}"

        # Get current date and time (format: YYYY-MM-DD HH:MM)
        CURRENT_DATE_TIME=$(date +'%Y-%m-%d %H:%M')

        # Define freeze period (start and end time)
        FREEZE_START="2024-10-03 10:10"
        FREEZE_END="2024-10-03 11:00"

        if [ "$CURRENT_BRANCH" == "$FROZEN_BRANCH" ]; then
          # Check if current time falls within the freeze period
          if [[ "$CURRENT_DATE_TIME" > "$FREEZE_START" && "$CURRENT_DATE_TIME" < "$FREEZE_END" ]]; then
            echo "Branch is frozen! Pushes are not allowed between $FREEZE_START and $FREEZE_END."
            exit 1  # Exit with error to fail the pipeline
          else
            echo "Push is allowed. Outside of freeze time."
          fi
        else
          echo "Not on the frozen branch."
        fi
